color_theme = "Default"
truecolor = true
rounded_corners = true
graph_symbol = "braille"
update_ms = 2000
proc_mem_bytes = true
temp_scale = "celsius"
show_disks = true
show_swap = true
save_config_on_exit = false
